.github/workflows/python37.yml
.github/workflows/python38.yml
.github/workflows/python39.yml
examples/rl/Howto 16 - (RL) Model Based Reinforcement Learning.py
src/mlpro/bf/math.py
src/mlpro/rl/models_env.py
src/mlpro/rl/pool/envmodels/mlpenvmodel.py
src/mlpro/rl/pool/envs/robotinhtm.py
src/mlpro/sl/pool/afct/mlpafctrans.py
src/mlpro/wrappers/sb3.py

Model Based Reinforcement Learning

---

setup.cfg
src/setup.py

Correction setup.cfg

---

.github/workflows/python37.yml
.github/workflows/python38.yml
.github/workflows/python39.yml
examples/rl/Howto 14 - (RL) Train UR5 with SB3 wrapper.py
examples/rl/Howto 18 - (RL) Single Agent with stagnation detection and SB3 Wrapper.py
src/mlpro/rl/pool/envs/ur5jointcontrol/src/reinforcement_learning/ur5_lab/config/ur5_simple_task_param.yaml
src/mlpro/rl/pool/envs/ur5jointcontrol/ur5jointcontrol.py
src/mlpro/wrappers/openai_gym.py
test/test_examples.py
test/test_sb3_policy_wrapper.py

Use the gym wrapper to wrap the UR5 environment

Ur5 fix and SB3 fixed using 1.3.0

---

src/mlpro/wrappers/pettingzoo.py

PettingZoo Wrapper Update

---

src/mlpro/rl/pool/envs/robotinhtm.py
src/mlpro/wrappers/openai_gym.py
test/test_sb3_policy_wrapper.py

OpenAi gym wrapper, SB3 test script, robotinhtm env

---

src/mlpro/rl/models_train.py

RL-Train: turned off training data logging on eval

---

src/mlpro/rl/models.py
src/mlpro/rl/models_agents.py
src/mlpro/rl/models_env.py
src/mlpro/rl/models_sar.py
src/mlpro/rl/models_train.py
src/mlpro/sl/models.py
src/mlpro/wrappers/openai_gym.py
src/mlpro/wrappers/sb3.py

Reformat Code

---

examples/rl/Howto 14 - (RL) Train UR5 with SB3 wrapper.py
examples/rl/Howto 15 - (RL) Train Robothtm with SB3 Wrapper.py
examples/rl/Howto 18 - (RL) Single Agent with stagnation detection and SB3 Wrapper.py
src/mlpro/rl/models_agents.py
src/mlpro/rl/models_sar.py
src/mlpro/rl/models_train.py
src/mlpro/rl/pool/envs/robotinhtm.py
src/mlpro/wrappers/sb3.py
test/test_sb3_policy_wrapper.py

Use deterministic for evaluation

---

src/mlpro/rl/models_agents.py

Update _adapt method in MultiAgent class

---

src/mlpro/rl/pool/envs/doublependulum.py

Double Pendulum Pool Env

---

examples/rl/Howto 17 - (RL) Advanced training with stagnation detection.py
src/mlpro/rl/models_train.py

RL-Train: new param p_stagnation_entry

---

examples/rl/Howto 17 - (RL) Advanced training with stagnation detection.py
src/mlpro/rl/models_train.py

RL-Train: Opt. continue after stagnation detection

---

src/mlpro/rl/models_agents.py

Minor Improvement on Class MultiAgent

---

.github/workflows/python37.yml
.github/workflows/python38.yml
.github/workflows/python39.yml
src/mlpro/wrappers/pettingzoo.py

Refactoring due to PettingZoo version 1.17.0

---

src/mlpro/wrappers/hyperopt.py
src/mlpro/wrappers/optuna.py

Optuna Wrapper: Change methods names

---

examples/bf/Howto 08 - (ML) Hyperparameter Tuning using Optuna.py
src/mlpro/wrappers/optuna.py

Optuna Wrapper: Add tuning recap visualization

---

.github/workflows/python37.yml
.github/workflows/python38.yml
.github/workflows/python39.yml
src/mlpro/wrappers/openai_gym.py

Wrapper Gym Enhancement

---

examples/rl/Howto 14a - (RL) Train UR5 with SB3 wrapper.py
src/mlpro/rl/pool/envs/ur5jointcontrol/ur5jointcontrol.py

Automate Build UR5 ROS Workspace

---

examples/rl/Howto 14a - (RL) Train UR5 with SB3 wrapper.py
src/mlpro/rl/pool/envs/ur5jointcontrol/src/reinforcement_learning/openai_ros/openai_ros/src/openai_ros/openai_ros_common.py
src/mlpro/rl/pool/envs/ur5jointcontrol/src/reinforcement_learning/openai_ros/openai_ros/src/openai_ros/task_envs/ur5_lab/simple_task.py

Add gazebo visualization GUI toggle for UR5

---

src/mlpro/rl/models_train.py
src/mlpro/rl/pool/envs/bglp.py

Bglp update

---

src/mlpro/wrappers/sb3.py

SB3 Wrapper: Enable the possibility to process reward type C_TYPE_EVERY_AGENT

---

src/mlpro/rl/pool/envs/bglp.py

Add termination condition for batch production scenario

---

src/mlpro/rl/pool/envs/bglp.py

Updating BGLP

---

src/mlpro/bf/ml.py
src/mlpro/gt/models.py
src/mlpro/wrappers/models.py

Renaming maturity to accuracy

---

src/mlpro/wrappers/sb3.py

SB3: HER Implementation

---

src/mlpro/rl/models_agents.py
src/mlpro/wrappers/pettingzoo.py

Minor improvement: _extract_observation method (Agent class) + PettingZoo

---

src/mlpro/rl/examples/howto_rl_wp_001_mlpro_environment_to_gym_environment.py
src/mlpro/rl/examples/howto_rl_wp_002_mlpro_environment_to_petting_zoo_environment.py
src/mlpro/rl/examples/howto_rl_wp_003_run_multiagent_with_own_policy_on_petting_zoo_environment.py

Bug fixing howto_rl_wp

---

src/mlpro/bf/ops.py
src/mlpro/rl/models_train.py

BF-Ops: Refactoring

---

src/mlpro/bf/examples/howto_bf_streams_010_accessing_data_from_openml.py
src/mlpro/bf/examples/howto_bf_streams_011_accessing_data_from_river.py
src/mlpro/bf/examples/howto_bf_streams_012_accessing_data_from_scikitlearn.py
src/mlpro/wrappers/openml.py
src/mlpro/wrappers/river.py
src/mlpro/wrappers/sklearn.py
test/test_examples.py

BF-Streams

---

src/mlpro/wrappers/pettingzoo.py
test/test_examples.py

Fix howto_rl_wp_003

---

.github/workflows/ci.yml
setup.cfg
src/mlpro/rl/examples/howto_rl_wp_001_mlpro_environment_to_gym_environment.py
src/setup.py

Installation option for mlpro "full"

---

.github/workflows/ci.yml
setup.cfg
src/mlpro/rl/examples/howto_rl_agent_001_run_agent_with_own_policy_on_gym_environment.py
src/mlpro/rl/examples/howto_rl_agent_002_train_agent_with_own_policy_on_gym_environment.py
src/mlpro/rl/examples/howto_rl_agent_005_train_and_reload_single_agent.py
src/mlpro/rl/examples/howto_rl_att_002_train_wrapped_sb3_policy_with_stagnation_detection.py
src/mlpro/rl/examples/howto_rl_wp_001_mlpro_environment_to_gym_environment.py
src/mlpro/rl/examples/howto_rl_wp_004_train_agent_with_sb3_policy.py
src/mlpro/rl/examples/howto_rl_wp_005_validation_wrapped_sb3_on_policy.py
src/mlpro/rl/examples/howto_rl_wp_006_validation_wrapped_sb3_off_policy.py
src/mlpro/rl/pool/envs/multicartpole.py
src/mlpro/wrappers/models.py
src/mlpro/wrappers/openai_gym.py
src/setup.py
test/test_sb3_policy_wrapper.py

Refactor compatibility for both gym version 0.21.0 and 0.25.0

---

src/mlpro/bf/math/unitconverter.py
src/mlpro/bf/systems.py

BF: Debugging on TransferFunction and UnitConverter

---

MANIFEST.in

WR : Added MuJoCo XML in MANIFEST.in

---

doc/rtd/conf.py

RTD: Bugfix of Control Element for Version Selection

---

README.md

https://img.shields.io/conda/dn/mlpro/mlpro?color=green&label=Anaconda.org%20Total%20downloads&style=flat-square

Add anaconda download badges on Readme

---

src/mlpro/bf/systems/pool/mujoco/mlpro.xml
src/mlpro/wrappers/mujoco.py

BF: Repositioning xyz arrow in MuJoCo

---

doc/rtd/content/02_basic_functions/mlpro_bf/sub/layer0_elementary/03_persistence.rst
doc/rtd/content/04_appendices/appendix2/sub/core/mlpro_sl/01_basics.rst

RTD: Typos, Class Diagram SL

---

src/mlpro/bf/math/basics.py
src/mlpro/sl/pool/afct/pytorch.py

SL: Refactoring PyTorch's Helper Functions

---

src/mlpro/wrappers/mujoco.py

WR: Add Offscreen Viewer MuJoCo and Camera Functionality

---

doc/rtd/content/02_basic_functions/mlpro_bf/sub/layer3_application_support/systems/01_mujoco_integration.rst
doc/rtd/content/04_appendices/appendix1/sub/mlpro_bf/layer3_application_support/systems/howto.bf.systems.004.rst
src/mlpro/bf/examples/howto_bf_systems_004_box_on_table_mujoco_simulation.py
src/mlpro/bf/systems/pool/mujoco/boxontable.xml
src/mlpro/bf/various.py
src/mlpro/wrappers/mujoco.py

WR: MuJoCo include body position and orientation as state, init MuJoCo state based on MLPro state space

---

src/mlpro/wrappers/mujoco.py

WR: Add MuJoCo camera fovy to state

---

src/mlpro/wrappers/mujoco.py

WR: MuJoCo add depth data to the state

---

src/mlpro/bf/ml/basics.py

BF-Model: Hyperparameter Updates through Event Handling

---

.github/workflows/marketplace.yml

Marketplace for MLPro

---

.github/workflows/marketplace.yml

Marketplace for MLPro (2)

---

src/mlpro/bf/math/geometry.py

Refact: Class bf.math.geometry.Point - Replace parent bf.math.Element(2)

---

doc/rtd/content/04_extensions/sub/01_extensions_org/org/fhswf/eet-fat-mt-kumar.rst

This PR was created automatically.

Automated PR

---

doc/rtd/content/04_extensions/sub/01_extensions_org/org/fhswf/eet-fat-mt-kumar.rst

This PR was created automatically.

Update Extension Hub

---

src/mlpro/oa/streams/helpers/change_observer.py

OA-Streams: Extensions of class OAStreamHelper
